=== ZON3DEV/AionReborn/Core/WorldServer/data/static_data/f14_events/events.xsd
<?xml version="1.0"?>
<!--
author flashman
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" elementFormDefault="qualified">
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" type="Event" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Event">
        <xs:sequence>
            <xs:element name="type" type="EventType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="event_id" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="map" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="schedule" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="registration_time" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="reentry_cooldown" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="cmd_name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="start_condition" type="EventStartCondition" minOccurs="0" maxOccurs="1"/>
            <xs:element name="start_position_info" type="EventStartPositions" minOccurs="1" maxOccurs="1"/>
            <xs:element name="reward_info" type="EventReward" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="EventStartCondition">
        <xs:sequence>
            <xs:element name="single_players_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
            <xs:element name="groups_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
            <xs:element name="players_for_each_group_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="EventStartPositions">
        <xs:sequence>
            <xs:element name="position" type="EventStartPosition" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="use_group" type="xs:boolean" use="required"/>
    </xs:complexType>
    <xs:complexType name="EventStartPosition">
        <xs:attribute name="x" type="xs:int" use="required"/>
        <xs:attribute name="y" type="xs:int" use="required"/>
        <xs:attribute name="z" type="xs:int" use="required"/>
        <xs:attribute name="h" type="xs:byte" use="optional"/>
        <xs:attribute name="group" type="xs:int" use="optional"/>
    </xs:complexType>
    <xs:complexType name="EventReward">
        <xs:sequence>
            <xs:element name="rank" type="Rank" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Rank">
        <xs:sequence>
            <xs:element name="reward_item_group" type="rItemGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="ap" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="gp" type="xs:int" use="optional" default="0"/>
    </xs:complexType>
    <xs:complexType name="rItemGroup">
        <xs:sequence>
            <xs:element name="item" type="rItem" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="random" type="xs:boolean" use="required"/>
        <xs:attribute name="random_count" type="xs:int" use="optional"/>
    </xs:complexType>
    <xs:complexType name="rItem">
        <xs:attribute name="item_id" type="xs:int" use="required"/>
        <xs:attribute name="count" type="xs:int" default="1"/>
    </xs:complexType>
    <xs:simpleType name="EventType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="E_1x1"/>
            <xs:enumeration value="E_2x2"/>
            <xs:enumeration value="E_3x3"/>
            <xs:enumeration value="E_4x4"/>
            <xs:enumeration value="E_6x6"/>
            <xs:enumeration value="E_LHE"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ZON3DEV/AionReborn/Core/WorldServer/data/static_data/f14_events/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
author: flashman
-->
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="events.xsd">
    <event>
        <type>E_1x1</type>
        <event_id>1</event_id>
        <map>300230000</map> <!-- Kromede's Trial -->
        <schedule>0 0 0/3 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>pvp 1x1</name>
        <cmd_name>pvp</cmd_name>
        <start_condition>
            <single_players_to_start>2</single_players_to_start>
            <groups_to_start>0</groups_to_start>
            <players_for_each_group_to_start>0</players_for_each_group_to_start>
        </start_condition>
        <start_position_info use_group="false">
            <position x="512" y="668" z="214" h="90"/>
            <position x="512" y="614" z="214" h="30"/>
        </start_position_info>
        <reward_info>
            <rank id="1" ap="7500" gp="0">
                <reward_item_group random="false">
                    <item item_id="186000242" count="10"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="10"/> <!-- Blood Mark -->                  
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="5"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="5"/> <!-- Blood Mark --> 
                </reward_item_group>
            </rank>
            <rank id="2" ap="3500">
                <reward_item_group random="false">
                    <item item_id="186000242" count="5"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="5"/> <!-- Blood Mark --> 
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="5"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="5"/> <!-- Blood Mark -->
                </reward_item_group>
            </rank>
        </reward_info>
    </event>
    <event>
        <type>E_2x2</type>
        <event_id>2</event_id>
        <map>301140000</map> <!-- Danuar Sanctuary -->
        <schedule>0 0 0/1 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>Group vs. Group 2x2</name>
        <cmd_name>2x2</cmd_name>
        <start_condition>
            <single_players_to_start>0</single_players_to_start>
            <groups_to_start>2</groups_to_start>
            <players_for_each_group_to_start>2</players_for_each_group_to_start>
        </start_condition>
        <start_position_info use_group="true">
            <position x="1056" y="579" z="280" h="32" group="1"/>
            <position x="1056" y="579" z="280" h="32" group="1"/>
            <position x="1056" y="782" z="280" h="88" group="2"/>
            <position x="1056" y="782" z="280" h="88" group="2"/>
        </start_position_info>
        <reward_info>
            <rank id="1" ap="7500" gp="0">
                <reward_item_group random="false">
                    <item item_id="186000242" count="20"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="20"/> <!-- Blood Mark -->                   
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="20"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="20"/> <!-- Blood Mark -->
                </reward_item_group>
            </rank>
        </reward_info>
    </event>
    <event>
        <type>E_3x3</type>
        <event_id>2</event_id>
        <map>320050000</map> <!-- Sky Temple -->
        <schedule>0 0 0/1 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>Group vs. Group 3x3</name>
        <cmd_name>3x3</cmd_name>
        <start_condition>
            <single_players_to_start>0</single_players_to_start>
            <groups_to_start>2</groups_to_start>
            <players_for_each_group_to_start>3</players_for_each_group_to_start>
        </start_condition>
        <start_position_info use_group="true">
            <position x="238" y="239" z="553" h="60" group="1"/>
            <position x="236" y="232" z="553" h="60" group="1"/>
            <position x="168" y="293" z="553" h="89" group="2"/>
            <position x="160" y="289" z="553" h="60" group="2"/>  
        </start_position_info>
        <reward_info>
            <rank id="1" ap="7500" gp="0">
                <reward_item_group random="false">
                    <item item_id="186000242" count="30"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="30"/> <!-- Blood Mark -->                  
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="30"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="30"/> <!-- Blood Mark -->
                </reward_item_group>
            </rank>
        </reward_info>
    </event>
    <event>
        <type>E_4x4</type>
        <event_id>2</event_id>
        <map>320080000</map> <!-- Draupnir Cave -->
        <schedule>0 0 0/1 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>Group vs. Group 4x4</name>
        <cmd_name>4x4</cmd_name>
        <start_condition>
            <single_players_to_start>0</single_players_to_start>
            <groups_to_start>2</groups_to_start>
            <players_for_each_group_to_start>4</players_for_each_group_to_start>
        </start_condition>
        <start_position_info use_group="true">
            <position x="812" y="492" z="318" h="80" group="1"/>
            <position x="812" y="492" z="318" h="80" group="1"/>
            <position x="812" y="492" z="318" h="80" group="1"/>                
            <position x="812" y="492" z="318" h="80" group="1"/>             
            <position x="710" y="437" z="319" h="119" group="2"/>
            <position x="710" y="437" z="319" h="119" group="2"/>
            <position x="710" y="437" z="319" h="119" group="2"/>                
            <position x="710" y="437" z="319" h="119" group="2"/>
        </start_position_info>
        <reward_info>
            <rank id="1" ap="7500" gp="0">
                <reward_item_group random="false">
                    <item item_id="186000242" count="40"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="40"/> <!-- Blood Mark -->                 
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="40"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="40"/> <!-- Blood Mark -->
                </reward_item_group>
            </rank>
        </reward_info>
    </event>
    <event>
        <type>E_6x6</type>
        <event_id>2</event_id>
        <map>301050000</map> <!-- Steel Rose Deck -->
        <schedule>0 0 0/1 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>Group vs. Group 6x6</name>
        <cmd_name>6x6</cmd_name>
        <start_condition>
            <single_players_to_start>0</single_players_to_start>
            <groups_to_start>2</groups_to_start>
            <players_for_each_group_to_start>6</players_for_each_group_to_start>
        </start_condition>
        <start_position_info use_group="true">
            <position x="489" y="510" z="1032" h="119" group="1"/>
            <position x="489" y="510" z="1032" h="119" group="1"/>
            <position x="489" y="510" z="1032" h="119" group="1"/>                
            <position x="489" y="510" z="1032" h="119" group="1"/>
            <position x="489" y="510" z="1032" h="119" group="1"/>
            <position x="489" y="510" z="1032" h="119" group="1"/>                
            <position x="614" y="510" z="1023" h="59" group="2"/>
            <position x="614" y="510" z="1023" h="59" group="2"/>
            <position x="614" y="510" z="1023" h="59" group="2"/>                
            <position x="614" y="510" z="1023" h="59" group="2"/>
            <position x="614" y="510" z="1023" h="59" group="2"/>
            <position x="614" y="510" z="1023" h="59" group="2"/>
        </start_position_info>
        <reward_info>
            <rank id="1" ap="7500" gp="0">
                <reward_item_group random="false">
                    <item item_id="186000242" count="60"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="60"/> <!-- Blood Mark -->                   
                </reward_item_group>
                <reward_item_group random="true" random_count="1">
                    <item item_id="186000242" count="60"/> <!-- Ceramium Medal -->
                    <item item_id="186000236" count="60"/> <!-- Blood Mark -->
                </reward_item_group>
            </rank>
        </reward_info>
    </event>
    <event>
        <type>E_LHE</type>
        <event_id>3</event_id>
        <map>301110000</map> <!-- Danuar Reliquary -->
        <schedule>0 0 0/1 ? * *</schedule>
        <registration_time>1200</registration_time>
        <reentry_cooldown>1200</reentry_cooldown>
        <name>Last Hero</name>
        <cmd_name>hero</cmd_name>
        <start_condition>
            <single_players_to_start>4</single_players_to_start>
            <groups_to_start>0</groups_to_start>
            <players_for_each_group_to_start>0</players_for_each_group_to_start>
        </start_condition>
